---
title: Homework Assignment 5
subtitle: Reshaping and Pivoting DataFrames [The Homework Assignment 5 may be subject to change during the Module.]
date: 2024-03-05
execute: 
  echo: false
  eval: false
  warning: false
  message: false
from: markdown+emoji
---

```{r}
#| echo: false

reticulate::use_condaenv("/Users/bchoe/anaconda3", required = TRUE)
```

# Direction

-   Write a Python code to answer each question.

-   Make at least some simple comment (`# ...`) in each question.

-   Import Python libraries you need here.

```{python}
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
```

<br><br><br>

# Question 1
Concatenate the two weeks of sales data into one DataFrame. Assign the week1 DataFrame a key of "`Week 1`" and the week2 DataFrame a key of "`Week 2`".

<br><br>

# Question 2
Find the customers who ate at the restaurant both weeks.

<br><br>


# Question 3
Find the customers who ate at the restaurant both weeks and ordered the same
item each week.

  - HINT You can join data sets on multiple columns by passing the on parameter
a list of columns.

<br><br>


# Question 4
Identify which customers came in only on Week 1 and only on Week 2.

<br><br>


# Question 5
Each row in the `week1` DataFrame identifies a customer who purchased a food item. For each row, pull in the customer’s information from the customers DataFrame.



<br><br><br>

# Discussion

<font size = "5">Hello everyone! Welcome to the Homework 5 Discussion Board! 🌟</font>

This board is all about connecting and discussing Homework 5 with your fellow students.

If you've got any questions for Byeong-Hak (**@bcdanl**) about the Homework 5 questions or need a bit more clarity on some parts, feel free to post them here.

Together, let's boost our understanding and make learning more fun!

