---
title: Homework 4
subtitle: Group Operations with GroupBy Objects [Homework 4 may be subject to change during the Module.]
date: 2024-02-27
execute: 
  echo: false
  eval: false
  warning: false
  message: false
from: markdown+emoji
comments: false
---

```{r}
#| echo: false

reticulate::use_condaenv("/Users/bchoe/anaconda3", required = TRUE)
```


# Direction

-   Write a Python code to answer each question.

-   Make at least some simple comment (`# ...`) in each question.

-   Import Python libraries you need here.

```{python}
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
```

<br><br><br>

# Question 1

Consider the `stock` DataFrame for Question 1.

```{python}
#| echo: true
path = 'https://bcdanl.github.io/data/stocks2013_2023.csv'
stock = pd.read_csv(path)
```

## Q1a

What are the minimum, first quartile, median, thrid quartile, maximum, mean, and standard deviation of `Close` and `Volume` for each `company`?
<br>

*Answer*

```{python}

```



## Q1b

Find the 10 largest values for `Volume`. What are the `companies` and `dates` associated with those 10 largest values for `Volume`?
<br>

*Answer*

```{python}

```



## Q1c

Calculate the Z-scores of `Open` and `Close` for each company using `apply()`.
<br>

*Answer*

```{python}

```



## Q1d

Use the `transform()` method on the `stock` data to represent all the values of `Open`, `High`, `Low`, `Close`, `Adj Close`, and `Volume` in terms of the first date in the data.

To do so, divide all values for each company by the values of the first date in the data for that company.
<br>

*Answer*

```{python}

```



## Q1e

Provide both seaborn code and a simple comment to describe the daily trend of normalized values of `Close` for each company in one plot. The normalized values of `Close` are the one calculated from Q1d.
<br>

*Answer*

```{python}

```



## Q1f

Create a box plot of `Close` for each `company` in one plot. Make a simple comment on the plot.
<br>

*Answer*

```{python}

```



# Question 2

Load the DataFrfame for Question 2.

```{python}
#| echo: true
path = 'https://bcdanl.github.io/data/climate_finance.csv'
climate_finance = pd.read_csv(path)
```

-   Adaptation involves taking actions to reduce the actual or expected damages from climate change.

-   Mitigation involves taking actions to reduce the emissions of greenhouse gases that are responsible for climate change.

## Q2a

How many `parties` have `provided` or `disbursed` positive funding `contributions` to other countries or regions for their `adaptation` projects for every single `year` from 2011 to 2018?
<br>

*Answer*

```{python}

```



## Q2b

For each `party`, calculate the total funding `contributions` that were `disbursed` or `provided` for `mitigation` projects for each `year`.
<br>

*Answer*

```{python}

```



## Q2c

For each `party`, calculate the ratio between `adaptation` contribution and `mitigation` contribution for each type of `Status` for each `year`.
<br>

*Answer*

```{python}

```



## Q2d

Provide both seaborn code and a simple comment to describe the distribution of the ratio between `adaptation` contribution and `mitigation` contribution, which is calculated in Q2c.
<br>

*Answer*

```{python}

```



## Q2e

Provide both seaborn code and a simple comment to describe how the distribution of `Contribution` varies by `Type of support` and `Status`.
<br>

*Answer*

```{python}

```




