---
title: Homework 6
subtitle: Group Oeprations 2; Pivoting Data; Joining Data
date: 2024-03-12
execute: 
  echo: false
  eval: false
  warning: false
  message: false
from: markdown+emoji
comments: false
---

```{r}
#| echo: false

reticulate::use_condaenv("/Users/bchoe/anaconda3", required = TRUE)
```

# Direction

-   Write a Python code to answer each question.

-   Make at least some simple comment (`# ...`) in each question.

-   Import Python libraries you need here.

```{python}
import pandas as pd
```

<br><br><br>


# Part 1

Load the DataFrfame for Question 2.

```{python}
#| echo: true
path = 'https://bcdanl.github.io/data/climate_finance.csv'
climate_finance = pd.read_csv(path)
```

-   Adaptation involves taking actions to reduce the actual or expected damages from climate change.

-   Mitigation involves taking actions to reduce the emissions of greenhouse gases that are responsible for climate change.

## Q2a

How many `parties` have `provided` or `disbursed` positive funding `contributions` to other countries or regions for their `adaptation` projects for every single `year` from 2011 to 2018?

```{python}

```

<br><br>

## Q2b

For each `party`, calculate the total funding `contributions` that were `disbursed` or `provided` for `mitigation` projects for each `year`.

```{python}

```

<br><br>

# Part 2

<br><br>

# Part 3

Citi Bike NYC is New York City’s official bike-sharing program. Residents and tourists can pick up and drop off bicycles at hundreds of locations around the city. Ride data is publicly available and released monthly by the city at [https://www.citibikenyc.com/system-data](https://www.citibikenyc.com/system-data). `citibike.csv` is a collection of ~1.9 million rides that cyclists took in June 2020. For simplicity’s sake, the data set has been modified from its original version and includes only two columns: each ride’s start time and end time. Let’s import the data set and assign it to a `citi_bike` variable:

```{python}
#| echo: true
citi_bike = pd.read_csv("citibike.csv")
```


# Question 1
Convert the start_time and stop_time columns to store datetime (`Timestamp`) values instead of strings.

<br><br>

# Question 2
Count the rides that occurred on each day of the week (Monday, Tuesday, and so on). Which weekday is the most popular for a bike ride? Use the start_time column as your starting point.

<br><br>

# Question 3
Count the rides per week for each week within the month. To do so, round each date in the start_time column to its previous or current Monday. Assume that each week starts on a Monday and ends on a Sunday. Thus, the first week of June would be Monday, June 1 through Sunday, June 7.

<br><br>

# Question 4
Calculate the duration of each ride, and save the results to a new duration column.

<br><br>

# Question 5
Find the average duration of a bike ride.

<br><br>

# Question 6
Extract the five longest bike rides by duration from the data set.




