---
title: Homework 1
subtitle: Python Basics
date: 2024-02-06
execute: 
  echo: false
  eval: false
  warning: false
  message: false
  
from: markdown+emoji
comments: false
---

```{r}
#| echo: false

reticulate::use_condaenv("/Users/bchoe/anaconda3", required = TRUE)
```


# Direction


- Please submit your Jupyter Notebook for Homework 1 to the Brightspace with the name below:

  - `danl-m1-hw1-LASTNAME-FIRSTNAME.ipynb`\
  ( e.g., `danl-m1-hw1-choe-byeonghak.ipynb` )

- The due is February 20, 2024, 3:30 P.M.

- Please send Byeong-Hak an email (`bchoe@geneseo.edu`) if you have any questions.

-   Write a Python Notebook (`*.ipynb`) to answer each question.

-   Make at least some simple comment (`# ...`) in each question.

-   Make one text cell to explain things in each question.


<!-- -   Use your working directory with the subfolder, `data`, so that the relative pathname of CSV files in the subfolder `data` is sufficient to import the CSV files. -->


<br><br>


# Question 1

How do you assign the value 5 to a variable named `x`?

*Answer*
```{python}

```

<br><br><br>


# Question 2

Given `lst = [1, 2, 3, 4, 5]`, what does `lst[1:4]` return?

*Answer*
```{python}

```

<br><br><br>

# Question 3

- How do you create a dictionary with keys `"apple"`, `"banana"`, and `"cherry"`, each with the corresponding values `5`, `3`, and `7`?

- How do you access the value associated with the key `"banana"` in the dictionary created above?

*Answer*
```{python}

```

<br><br><br>

# Question 4

For the expressions below, what is the value of the expression? Explain thoroughly.

```{python}
#| echo: true

True and False
```


```{python}
#| echo: true

True or False
```

```{python}
#| echo: true

not (100 == '100' and 25 < 36)
```


*Answer*
```{python}

```

<br><br><br>


# Question 5

- Create a new `if-elif-else` chain that prints `"well done"` if a score is over `90`, "good" if between `40` and `90`, and `"bad luck"` otherwise.

*Answer*
```{python}

```

<br><br><br>


# Question 6

Write a for loop that prints out `"coding for data analysts"` so that each word is printed in a successive iteration.

*Answer*
```{python}

```


<br><br><br>

# Question 7

- How do you import the `math` module in a Python script?
- After importing `math`, how do you use its `sqrt` function to find the square root of `16`?

*Answer*
```{python}

```

<br><br><br>


# Question 8

- Do Question 6 in [Classwork 1](https://bcdanl.github.io/module-1/danl-cw/danl-m1-cw-1.html#question-6)


<br><br><br>