---
title: Classwork 3
subtitle: Filtering, Sorting, Ranking, and Visualizing DataFrames [The Classwork 3 may be subject to change during the Module.]
date: 2024-02-20
execute: 
  eval: false
  echo: false
  warning: false
  message: false
---
# Load Data

```{python}
#| echo: true
import pandas as pd
df_ny = pd.read_csv('https://bcdanl.github.io/data/NY_pinc_pop.csv')
df_ny.head(10)
```

-   Variable Description
    -   `FIPS`: ID number for a county
    -   `pincp`: average personal income in a county `X` in year `Y`
    -   `pop_18_24`: population 18 to 24 years
    -   `pop_25_over`: population 25 years and over

# Q1a

-   Use `.sort_values()` to find the top 5 rich counties in NY for each year.
    -   Do not use `.apply()`.

<br>

*Answer*
```{python}

```

# Q1b

-   Use `.rank()` to find the top 5 rich counties in NY for each year.
    -   Do not use `apply()`.

<br>

*Answer*
```{python}

```

# Q1c

-   Use `apply()` with a `lambda` function and `.sort_values()` to find the top 5 rich counties in NY for each year.
<br>

*Answer*
```{python}

```

# Q1d

-   Write a function with `def` and `.sort_values()` that selects the top 5 `pincp` values.

-   Then, use the `def`ined function in `apply()` to find the top 5 rich counties in NY for each year.
<br>

*Answer*
```{python}

```



# Q1e

-   Visualize the yearly trend of the mean level of `pincp`.
<br>

*Answer*
```{python}

```


<br><br><br>
  
# Discussion

<font size = "5">Hello everyone! Welcome to our Classwork 1 Discussion Board! 🌟 </font>

This board is here for you to connect with peer classmates over the content presented in Classwork 1. 

If you have specific questions for Byeong-Hak (**@bcdanl**) related to Classwork 1 or if you're seeking more detailed explanations on any topics, don't hesitate to post them here.

Let's work together and enrich our learning experience!

