---
title: Classwork 7
subtitle: Missing Data; Time-series Data [The Classwork 7 may be subject to change during the Module.]
date: 2024-03-19
execute: 
  eval: false
  echo: false
  warning: false
  message: false
---

## Load Libraries

```{python}
#| echo: true
import pandas as pd
import numpy as np
import seaborn as sns
```

<br>

# Question 1


Consider the following example DataFrames.
```{python}
#| echo: true
banks = pd.read_csv('https://bcdanl.github.io/data/bank_failures.csv', parse_dates=["Closing Date"])

```

<br>

## Q1a
Add the new variables, `closing_quarter` and `closing_year`, to the DataFrame `banks`.
  - `closing_quarter`:  the quarter in which the bank closed (`1`, `2`, `3`, or `4`)
  - `closing_year`:  the year in which the bank closed


<br>


<br>

*Answer*
```{python}

```



## Q1b
Count the number of banks that were closed for each pair of year-quarter.


<br>

*Answer*
```{python}

```



<br>

## Q1c
Provide both seaborn code and a simple comment to describe the quarterly trend of bank failure.


<br>

*Answer*
```{python}

```



<br><br><br>

# Question 2

Consider the following stock data:

```{python}
path = 'https://bcdanl.github.io/data/stocks2013_2023.csv'
stock = pd.read_csv(path)
```

<br>

## Q2a

Add a variable, `date_dt`, which is a `datetime` type of `Date` variable, to the `stock` DataFrame.


<br>

*Answer*
```{python}

```


<br>

## Q2b

- For each year, find the two dates, for which 
  - `TSLA`'s `Close` was the highest of the year.
  - `TSLA`'s `Close` was the lowest of the year.
  



<br>

*Answer*
```{python}

```




<br>

## Q2c
- Calculate the gap between the two adjacent dates with the highest `Close` of the year.

- Calculate the gap between the two adjacent dates with the lowest `Close` of the year.



<br>

*Answer*
```{python}

```




<br><br><br>
  
# Discussion

<font size = "5">Hello everyone! Welcome to our Classwork 1 Discussion Board! 🌟 </font>

This board is here for you to connect with peer classmates over the content presented in Classwork 1. 

If you have specific questions for Byeong-Hak (**@bcdanl**) related to Classwork 1 or if you're seeking more detailed explanations on any topics, don't hesitate to post them here.

Let's work together and enrich our learning experience!
