---
title: Classwork 4
subtitle: Group Operations with GroupBy Objects [The Classwork 4 may be subject to change during the Module.]
date: 2024-02-27
execute: 
  eval: false
  echo: false
  warning: false
  message: false
---

## Load Libraries

```{python}
#| echo: true
import pandas as pd
import numpy as np
import seaborn as sns
```

# Question 1

## Load `DataFrame`

```{python}
#| echo: true
#| eval: false
beer_mkt = pd.read_csv('https://bcdanl.github.io/data/beer_markets.csv')
beer_mkt.head(10)
```

-   Variable Description
    -   `hh`: An identifier of the purchasing household;
    -   `_purchase_desc`: Details on the purchased item;
    -   `quantity`: Number of items purchased;
    -   `brand`: BUD LIGHT, BUSCH LIGHT, COORS LIGHT, MILLER LITE, or NATURAL LIGHT;
    -   `spent`: Total dollar value of purchase;
    -   `beer_floz`: Total volume of beer, in fluid ounces;
    -   `price_per_floz`: Price per fl.oz. (i.e., `spent`/`beer_floz`);
    -   `container`: Type of container;
    -   `promo`: Whether the item was promoted (coupon or something else);
    -   `market`: Scan-track market (or state if rural);
    -   various demographic data, including gender, marital status, household income, class of work, race, education, age, the size of household, and whether or not the household has a microwave or a dishwasher.

<br><br>

## Q1a

-   Sort the DataFrame `beer_mkt` by `hh` in ascending order.
<br>

*Answer*
```{python}

```

## Q1b

-   Find the top 5 beer markets in terms of the number of households that purchased beer.
<br>

*Answer*
```{python}

```

## Q1c

-   Find the top 5 beer markets in terms of the amount of total beer consumption.
<br>

*Answer*
```{python}

```

## Q1d

-   Provide (1) seaborn code and (2) a simple comment to describe how the distribution of `price_per_floz` varies by `brand`.
<br>

*Answer*
```{python}

```

## Q1e

-   Provide (1) seaborn code and (2) a simple comment to describe how the relationship between `price_per_floz` and `beer_floz` varies by `brand`.
<br>

*Answer*
```{python}

```



<br><br><br>
  
# Discussion

<font size = "5">Hello everyone! Welcome to our Classwork 1 Discussion Board! 🌟 </font>

This board is here for you to connect with peer classmates over the content presented in Classwork 1. 

If you have specific questions for Byeong-Hak (**@bcdanl**) related to Classwork 1 or if you're seeking more detailed explanations on any topics, don't hesitate to post them here.

Let's work together and enrich our learning experience!


