---
title: Classwork 5
subtitle: Reshaping and Pivoting DataFrames [The Classwork 5 may be subject to change during the Module.]
date: 2024-03-05
execute: 
  eval: false
  echo: false
  warning: false
  message: false
---

## Load Libraries

```{python}
#| echo: true
import pandas as pd
import numpy as np
import seaborn as sns
```

# Question 1

## Load `DataFrame`

```{python}
#| echo: true
#| eval: false
billboard = pd.read_csv('https://bcdanl.github.io/data/billboard.csv')
ny_pincp = pd.read_csv('https://bcdanl.github.io/data/NY_pinc_wide.csv')
covid = pd.read_csv('https://bcdanl.github.io/data/covid19_cases.csv')
```

## Q1a

-   Describe how the distribution of rating varies across week 1, week 2, and week 3 using the **faceted** histogram.
<br>

*Answer*
```{python}

```

## Q1b

-   Which artist(s) have the most number of tracks in `billboard` DataFrame?
<br>

*Answer*
```{python}

```


## Q1c

-   Make `ny_pincp` longer.

<br>

*Answer*
```{python}

```


## Q1d

-   Make a wide-form DataFrame of `covid` whose variable names are from `countriesAndTerritories` and values are from `cases`.

<br>

*Answer*
```{python}

```

## Q1e

-   Use the wide-form DataFrame of `covid` to find the top 10 countries for which their cases are highly correlated with USA's cases using `DataFrame.corr()`

<br>

*Answer*
```{python}

```


<br><br><br>

# Question 2

## Load DataFrame for Q2a and Q2b

```{python}
#| echo: true
#| eval: false
paidsearch = pd.read_csv('https://bcdanl.github.io/data/paidsearch.csv')
```

-   Variable description
    -   `dma`: an identification number of a designated market (DM) area `i` (e.g., Boston, Los Angeles)
    -   `treatment_period`: 0 if date is before May 22, 2012 and 1 after.
    -   `search_stays_on`: 1 if the paid-search goes off in dma `i`, 0 otherwise.
    -   `revenue`: eBay's sales revenue for dma `i` and date `t`

## Q2a

Summarize the mean vale of `revenue` for each group of `search_stays_on` and for each `date`.

<br>

*Answer*
```{python}

```


<br>

## Q2b

Calculate the log difference between mean revenues in each group of `search_stays_on`. (This is the log of the average revenue in group of search_stays_on == 1 minus the log of the average revenue in group of search_stays_on == 0.)

-   For example, consider the following two observations:

```{python}
# date        the daily mean vale of `revenue`   search_stays_on
# 1-Apr-12    93650.68                           0
# 1-Apr-12    120277.57                          1
```

-   The log difference of daily mean revenues between the two group of `search_stays_on` for date 1-Apr-12 is log(120277.57) - log(93650.68).

<br>

*Answer*
```{python}

```


<br>

## Load DataFrame for Q2c, Q2d, and Q2e

```{python}
#| echo: true
#| eval: false
paid_search = pd.read_csv('https://bcdanl.github.io/data/paid_search.csv')
```

<br>

## Q2C

Sort `paid_search` by `DM` and `May22_2012` in ascending order.

<br>

*Answer*
```{python}

```

<br>

## Q2d

For each `DM`, calculate the difference between `log_revenue` before and after `May22_2012`.

<br>

*Answer*
```{python}

```


<br>

## Q2e

-   Consider the DataFrame from Q2d.

-   For each group of `no_paid_search`, calculate the mean value of the difference between `log_revenue` before and after `May22_2012` .

-   What is the difference in the mean values?

-   After the paid-search went off, sales revenue decreased by 0.66%
    -   Was eBay's paid search worth it?
    

<br>

*Answer*
```{python}

```




<br><br><br>
  
# Discussion

<font size = "5">Hello everyone! Welcome to our Classwork 1 Discussion Board! 🌟 </font>

This board is here for you to connect with peer classmates over the content presented in Classwork 1. 

If you have specific questions for Byeong-Hak (**@bcdanl**) related to Classwork 1 or if you're seeking more detailed explanations on any topics, don't hesitate to post them here.

Let's work together and enrich our learning experience!
