---
title: Classwork 2
subtitle: Pandas Basics
date: 2024-02-13
execute: 
  eval: false
  echo: false
  warning: false
  message: false
  
from: markdown+emoji
---

```{r}
#| echo: false

reticulate::use_condaenv("/Users/bchoe/anaconda3", required = TRUE)
```

# Direction


:::: {.columns}

::: {.column width="50%"}

The `nfl.csv` file contains a list of players in the National Football League with similar `Name`, `Team`, `Position`, `Birthday`, and `Salary` variables in the `nba.csv` file. 

:::


::: {.column width="50%"}
[](https://bcdanl.github.io/lec_figs/nfl-logo.png)
:::

::::

```{python}
#| echo: true
import pandas as pd
nfl = pd.read_csv("https://bcdanl.github.io/data/nfl.csv")
```

<br><br>

# Question 1
- How can we read the *nfl.csv* file, and assign it to a `DataFrame` object, `nfl`? 
- What is an effective way to convert the values in its `Birthday` variable to `datetimes`?

*Answer:*
```{python}

```

<br>

# Question 2

How can we set the `DataFrame` index to store the player names?

*Answer:*
```{python}

```

<br>


# Question 3
- How many observations are in `nfl`?
- What are the mean, median, standard deviation, minimum, and maximum of `Salary` in `nfl`?

*Answer:*
```{python}

```

<br>

# Question 4
- How can we count the number of players per team in `nfl`?
- How many unique teams are in `nfl`?

*Answer:*
```{python}

```

<br>

# Question 5
- Who are the five highest-paid players?
- Who is the oldest player?

*Answer:*
```{python}

```

<br>

# Question 6
How can we sort the `DataFrame` first by `Team` in alphabetical order and then by `Salary` in descending order?

*Answer:*
```{python}

```

<br>


# Question 7
Who is the oldest player on the `New York Jets` roster, and what is his birthday?

*Answer:*
```{python}

```

<br>


# Discussion

<font size = "5">Welcome to our Classwork 2 Discussion Board! 👋 </font>


This space is designed for you to engage with your classmates about the material covered in Classwork 2.

Whether you are looking to delve deeper into the content, share insights, or have questions about the content, this is the perfect place for you.

If you have any specific questions for Byeong-Hak (**@bcdanl**) regarding the Classwork 2 materials or need clarification on any points, don't hesitate to ask here. 

Let's collaborate and learn from each other!


