---
title: Classwork 1
subtitle: Python Basics
date: 2024-02-06
execute: 
  eval: false
  echo: false
  warning: false
  message: false
  
from: markdown+emoji
---

```{r}
#| echo: false

reticulate::use_condaenv("/Users/bchoe/anaconda3", required = TRUE)
```



# Question 1

```{python}
#| echo: true
list_variable = [100, 144, 169, 1000, 8]
```


Write a Python code that uses `print()` and `max()` functions to print out the largest value in the list, `list_variable`, as follows:

<div style="font-family:courier">The largest value in the list is: 1000</div>
<div style="font-family:courier">The smallest value in the list is: 8</div>




<br>

*Answer*
```{python}

```



<br><br><br> 

# Question 2

```{python}
#| echo: true
fare = "$10.00"
tip = "2.00$"
tax = "$ 0.80"
```


Write a Python code that uses *slicing* and the `print()` function to print out the following message: 

<div style="font-family:courier">The total trip cost is: $12.80</div>




<br>

*Answer*
```{python}

```

    
<br><br><br>

# Question 3

```{python}
#| echo: true
x = 4.0
y = .5
```


For each expression below, what is the value of the expression? Explain thoroughly.

```{python}
#| echo: true
20 == '20'
bool(0) != bool('')
x < y or 3*y < x
not (100 == '100' and 25 < 36)
```


<br>

*Answer*
```{python}

```

<br><br><br>

# Question 4

This Python code creates a tuple with seven different ages:

```{python}
#| echo: true
respondent_ages = (65, 29, 25, 35, 58, 23, 19)
```

Write a Python code that uses a *for-loop* statement and a *if-else* statement to assign the list, `under40_list`, to `[29, 25, 35, 23, 19]` and the list, `over40_list`, to `[65, 58]`.


<br>

*Answer*
```{python}

```

<br><br><br>

# Question 5

```{python}
#| echo: true
tuple_var = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
total = 0
```

Write a Python code that uses the following two lines (1) a *for-loop* statement to process each element of `tuple_var` and (2) the following line.

```{python}
#| echo: true
print("The total of the values in the tuple is: ", total)
```


<br>

*Answer*
```{python}

```


<br><br><br>
  
# Question 6

Write a Python code that uses a *while-loop* and the `print()` function to print out the following message 5 times:

<div style="font-family:courier">Programming for Data Analytics is so fun!</div>


<br>

*Answer*
```{python}

```


<br><br><br>
  
# Discussion

<font size = "5">Hello everyone! Welcome to our Classwork 1 Discussion Board! 🌟 </font>

This board is here for you to connect with peer classmates over the content presented in Classwork 1. 

If you have specific questions for Byeong-Hak (**@bcdanl**) related to Classwork 1 or if you're seeking more detailed explanations on any topics, don't hesitate to post them here.

Let's work together and enrich our learning experience!